// Code generated by entc, DO NOT EDIT.

package course

const (
	// Label holds the string label denoting the course type in the database.
	Label = "course"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCOURSE holds the string denoting the course field in the database.
	FieldCOURSE = "course"

	// EdgeBookcourse holds the string denoting the bookcourse edge name in mutations.
	EdgeBookcourse = "bookcourse"
	// EdgePromotion holds the string denoting the promotion edge name in mutations.
	EdgePromotion = "promotion"

	// Table holds the table name of the course in the database.
	Table = "courses"
	// BookcourseTable is the table the holds the bookcourse relation/edge.
	BookcourseTable = "bookcourses"
	// BookcourseInverseTable is the table name for the Bookcourse entity.
	// It exists in this package in order to avoid circular dependency with the "bookcourse" package.
	BookcourseInverseTable = "bookcourses"
	// BookcourseColumn is the table column denoting the bookcourse relation/edge.
	BookcourseColumn = "course_bookcourse"
	// PromotionTable is the table the holds the promotion relation/edge.
	PromotionTable = "promotions"
	// PromotionInverseTable is the table name for the Promotion entity.
	// It exists in this package in order to avoid circular dependency with the "promotion" package.
	PromotionInverseTable = "promotions"
	// PromotionColumn is the table column denoting the promotion relation/edge.
	PromotionColumn = "course_promotion"
)

// Columns holds all SQL columns for course fields.
var Columns = []string{
	FieldID,
	FieldCOURSE,
}
