// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Age is the predicate function for age builders.
type Age func(*sql.Selector)

// Bookcourse is the predicate function for bookcourse builders.
type Bookcourse func(*sql.Selector)

// Classifier is the predicate function for classifier builders.
type Classifier func(*sql.Selector)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Equipment is the predicate function for equipment builders.
type Equipment func(*sql.Selector)

// Equipmentrental is the predicate function for equipmentrental builders.
type Equipmentrental func(*sql.Selector)

// Equipmenttype is the predicate function for equipmenttype builders.
type Equipmenttype func(*sql.Selector)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// Paymenttype is the predicate function for paymenttype builders.
type Paymenttype func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Promotion is the predicate function for promotion builders.
type Promotion func(*sql.Selector)

// Promotionamount is the predicate function for promotionamount builders.
type Promotionamount func(*sql.Selector)

// Promotiontime is the predicate function for promotiontime builders.
type Promotiontime func(*sql.Selector)

// Promotiontype is the predicate function for promotiontype builders.
type Promotiontype func(*sql.Selector)

// Salary is the predicate function for salary builders.
type Salary func(*sql.Selector)

// Zone is the predicate function for zone builders.
type Zone func(*sql.Selector)
