// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/G16/app/ent/age"
	"github.com/G16/app/ent/employee"
	"github.com/G16/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// AgeUpdate is the builder for updating Age entities.
type AgeUpdate struct {
	config
	hooks      []Hook
	mutation   *AgeMutation
	predicates []predicate.Age
}

// Where adds a new predicate for the builder.
func (au *AgeUpdate) Where(ps ...predicate.Age) *AgeUpdate {
	au.predicates = append(au.predicates, ps...)
	return au
}

// SetAGE sets the AGE field.
func (au *AgeUpdate) SetAGE(i int) *AgeUpdate {
	au.mutation.ResetAGE()
	au.mutation.SetAGE(i)
	return au
}

// AddAGE adds i to AGE.
func (au *AgeUpdate) AddAGE(i int) *AgeUpdate {
	au.mutation.AddAGE(i)
	return au
}

// AddEmployeeIDs adds the employee edge to Employee by ids.
func (au *AgeUpdate) AddEmployeeIDs(ids ...int) *AgeUpdate {
	au.mutation.AddEmployeeIDs(ids...)
	return au
}

// AddEmployee adds the employee edges to Employee.
func (au *AgeUpdate) AddEmployee(e ...*Employee) *AgeUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return au.AddEmployeeIDs(ids...)
}

// Mutation returns the AgeMutation object of the builder.
func (au *AgeUpdate) Mutation() *AgeMutation {
	return au.mutation
}

// RemoveEmployeeIDs removes the employee edge to Employee by ids.
func (au *AgeUpdate) RemoveEmployeeIDs(ids ...int) *AgeUpdate {
	au.mutation.RemoveEmployeeIDs(ids...)
	return au
}

// RemoveEmployee removes employee edges to Employee.
func (au *AgeUpdate) RemoveEmployee(e ...*Employee) *AgeUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return au.RemoveEmployeeIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (au *AgeUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(au.hooks) == 0 {
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AgeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AgeUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AgeUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AgeUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AgeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   age.Table,
			Columns: age.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: age.FieldID,
			},
		},
	}
	if ps := au.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.AGE(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: age.FieldAGE,
		})
	}
	if value, ok := au.mutation.AddedAGE(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: age.FieldAGE,
		})
	}
	if nodes := au.mutation.RemovedEmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   age.EmployeeTable,
			Columns: []string{age.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employee.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   age.EmployeeTable,
			Columns: []string{age.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employee.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{age.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// AgeUpdateOne is the builder for updating a single Age entity.
type AgeUpdateOne struct {
	config
	hooks    []Hook
	mutation *AgeMutation
}

// SetAGE sets the AGE field.
func (auo *AgeUpdateOne) SetAGE(i int) *AgeUpdateOne {
	auo.mutation.ResetAGE()
	auo.mutation.SetAGE(i)
	return auo
}

// AddAGE adds i to AGE.
func (auo *AgeUpdateOne) AddAGE(i int) *AgeUpdateOne {
	auo.mutation.AddAGE(i)
	return auo
}

// AddEmployeeIDs adds the employee edge to Employee by ids.
func (auo *AgeUpdateOne) AddEmployeeIDs(ids ...int) *AgeUpdateOne {
	auo.mutation.AddEmployeeIDs(ids...)
	return auo
}

// AddEmployee adds the employee edges to Employee.
func (auo *AgeUpdateOne) AddEmployee(e ...*Employee) *AgeUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return auo.AddEmployeeIDs(ids...)
}

// Mutation returns the AgeMutation object of the builder.
func (auo *AgeUpdateOne) Mutation() *AgeMutation {
	return auo.mutation
}

// RemoveEmployeeIDs removes the employee edge to Employee by ids.
func (auo *AgeUpdateOne) RemoveEmployeeIDs(ids ...int) *AgeUpdateOne {
	auo.mutation.RemoveEmployeeIDs(ids...)
	return auo
}

// RemoveEmployee removes employee edges to Employee.
func (auo *AgeUpdateOne) RemoveEmployee(e ...*Employee) *AgeUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return auo.RemoveEmployeeIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (auo *AgeUpdateOne) Save(ctx context.Context) (*Age, error) {

	var (
		err  error
		node *Age
	)
	if len(auo.hooks) == 0 {
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AgeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			mut = auo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AgeUpdateOne) SaveX(ctx context.Context) *Age {
	a, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return a
}

// Exec executes the query on the entity.
func (auo *AgeUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AgeUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AgeUpdateOne) sqlSave(ctx context.Context) (a *Age, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   age.Table,
			Columns: age.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: age.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Age.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := auo.mutation.AGE(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: age.FieldAGE,
		})
	}
	if value, ok := auo.mutation.AddedAGE(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: age.FieldAGE,
		})
	}
	if nodes := auo.mutation.RemovedEmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   age.EmployeeTable,
			Columns: []string{age.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employee.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   age.EmployeeTable,
			Columns: []string{age.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: employee.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	a = &Age{config: auo.config}
	_spec.Assign = a.assignValues
	_spec.ScanValues = a.scanValues()
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{age.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return a, nil
}
