// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/G16/app/ent/equipment"
	"github.com/G16/app/ent/equipmentrental"
	"github.com/G16/app/ent/equipmenttype"
	"github.com/G16/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// EquipmenttypeUpdate is the builder for updating Equipmenttype entities.
type EquipmenttypeUpdate struct {
	config
	hooks      []Hook
	mutation   *EquipmenttypeMutation
	predicates []predicate.Equipmenttype
}

// Where adds a new predicate for the builder.
func (eu *EquipmenttypeUpdate) Where(ps ...predicate.Equipmenttype) *EquipmenttypeUpdate {
	eu.predicates = append(eu.predicates, ps...)
	return eu
}

// SetEQUIPMENTTYPE sets the EQUIPMENTTYPE field.
func (eu *EquipmenttypeUpdate) SetEQUIPMENTTYPE(s string) *EquipmenttypeUpdate {
	eu.mutation.SetEQUIPMENTTYPE(s)
	return eu
}

// AddEquipmentIDs adds the equipment edge to Equipment by ids.
func (eu *EquipmenttypeUpdate) AddEquipmentIDs(ids ...int) *EquipmenttypeUpdate {
	eu.mutation.AddEquipmentIDs(ids...)
	return eu
}

// AddEquipment adds the equipment edges to Equipment.
func (eu *EquipmenttypeUpdate) AddEquipment(e ...*Equipment) *EquipmenttypeUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return eu.AddEquipmentIDs(ids...)
}

// AddEquipmentrentalIDs adds the equipmentrental edge to Equipmentrental by ids.
func (eu *EquipmenttypeUpdate) AddEquipmentrentalIDs(ids ...int) *EquipmenttypeUpdate {
	eu.mutation.AddEquipmentrentalIDs(ids...)
	return eu
}

// AddEquipmentrental adds the equipmentrental edges to Equipmentrental.
func (eu *EquipmenttypeUpdate) AddEquipmentrental(e ...*Equipmentrental) *EquipmenttypeUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return eu.AddEquipmentrentalIDs(ids...)
}

// Mutation returns the EquipmenttypeMutation object of the builder.
func (eu *EquipmenttypeUpdate) Mutation() *EquipmenttypeMutation {
	return eu.mutation
}

// RemoveEquipmentIDs removes the equipment edge to Equipment by ids.
func (eu *EquipmenttypeUpdate) RemoveEquipmentIDs(ids ...int) *EquipmenttypeUpdate {
	eu.mutation.RemoveEquipmentIDs(ids...)
	return eu
}

// RemoveEquipment removes equipment edges to Equipment.
func (eu *EquipmenttypeUpdate) RemoveEquipment(e ...*Equipment) *EquipmenttypeUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return eu.RemoveEquipmentIDs(ids...)
}

// RemoveEquipmentrentalIDs removes the equipmentrental edge to Equipmentrental by ids.
func (eu *EquipmenttypeUpdate) RemoveEquipmentrentalIDs(ids ...int) *EquipmenttypeUpdate {
	eu.mutation.RemoveEquipmentrentalIDs(ids...)
	return eu
}

// RemoveEquipmentrental removes equipmentrental edges to Equipmentrental.
func (eu *EquipmenttypeUpdate) RemoveEquipmentrental(e ...*Equipmentrental) *EquipmenttypeUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return eu.RemoveEquipmentrentalIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (eu *EquipmenttypeUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EquipmenttypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EquipmenttypeUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EquipmenttypeUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EquipmenttypeUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eu *EquipmenttypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   equipmenttype.Table,
			Columns: equipmenttype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: equipmenttype.FieldID,
			},
		},
	}
	if ps := eu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.EQUIPMENTTYPE(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: equipmenttype.FieldEQUIPMENTTYPE,
		})
	}
	if nodes := eu.mutation.RemovedEquipmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipmenttype.EquipmentTable,
			Columns: []string{equipmenttype.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.EquipmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipmenttype.EquipmentTable,
			Columns: []string{equipmenttype.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := eu.mutation.RemovedEquipmentrentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipmenttype.EquipmentrentalTable,
			Columns: []string{equipmenttype.EquipmentrentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipmentrental.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.EquipmentrentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipmenttype.EquipmentrentalTable,
			Columns: []string{equipmenttype.EquipmentrentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipmentrental.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{equipmenttype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// EquipmenttypeUpdateOne is the builder for updating a single Equipmenttype entity.
type EquipmenttypeUpdateOne struct {
	config
	hooks    []Hook
	mutation *EquipmenttypeMutation
}

// SetEQUIPMENTTYPE sets the EQUIPMENTTYPE field.
func (euo *EquipmenttypeUpdateOne) SetEQUIPMENTTYPE(s string) *EquipmenttypeUpdateOne {
	euo.mutation.SetEQUIPMENTTYPE(s)
	return euo
}

// AddEquipmentIDs adds the equipment edge to Equipment by ids.
func (euo *EquipmenttypeUpdateOne) AddEquipmentIDs(ids ...int) *EquipmenttypeUpdateOne {
	euo.mutation.AddEquipmentIDs(ids...)
	return euo
}

// AddEquipment adds the equipment edges to Equipment.
func (euo *EquipmenttypeUpdateOne) AddEquipment(e ...*Equipment) *EquipmenttypeUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return euo.AddEquipmentIDs(ids...)
}

// AddEquipmentrentalIDs adds the equipmentrental edge to Equipmentrental by ids.
func (euo *EquipmenttypeUpdateOne) AddEquipmentrentalIDs(ids ...int) *EquipmenttypeUpdateOne {
	euo.mutation.AddEquipmentrentalIDs(ids...)
	return euo
}

// AddEquipmentrental adds the equipmentrental edges to Equipmentrental.
func (euo *EquipmenttypeUpdateOne) AddEquipmentrental(e ...*Equipmentrental) *EquipmenttypeUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return euo.AddEquipmentrentalIDs(ids...)
}

// Mutation returns the EquipmenttypeMutation object of the builder.
func (euo *EquipmenttypeUpdateOne) Mutation() *EquipmenttypeMutation {
	return euo.mutation
}

// RemoveEquipmentIDs removes the equipment edge to Equipment by ids.
func (euo *EquipmenttypeUpdateOne) RemoveEquipmentIDs(ids ...int) *EquipmenttypeUpdateOne {
	euo.mutation.RemoveEquipmentIDs(ids...)
	return euo
}

// RemoveEquipment removes equipment edges to Equipment.
func (euo *EquipmenttypeUpdateOne) RemoveEquipment(e ...*Equipment) *EquipmenttypeUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return euo.RemoveEquipmentIDs(ids...)
}

// RemoveEquipmentrentalIDs removes the equipmentrental edge to Equipmentrental by ids.
func (euo *EquipmenttypeUpdateOne) RemoveEquipmentrentalIDs(ids ...int) *EquipmenttypeUpdateOne {
	euo.mutation.RemoveEquipmentrentalIDs(ids...)
	return euo
}

// RemoveEquipmentrental removes equipmentrental edges to Equipmentrental.
func (euo *EquipmenttypeUpdateOne) RemoveEquipmentrental(e ...*Equipmentrental) *EquipmenttypeUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return euo.RemoveEquipmentrentalIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (euo *EquipmenttypeUpdateOne) Save(ctx context.Context) (*Equipmenttype, error) {

	var (
		err  error
		node *Equipmenttype
	)
	if len(euo.hooks) == 0 {
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EquipmenttypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			mut = euo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, euo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EquipmenttypeUpdateOne) SaveX(ctx context.Context) *Equipmenttype {
	e, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return e
}

// Exec executes the query on the entity.
func (euo *EquipmenttypeUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EquipmenttypeUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (euo *EquipmenttypeUpdateOne) sqlSave(ctx context.Context) (e *Equipmenttype, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   equipmenttype.Table,
			Columns: equipmenttype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: equipmenttype.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Equipmenttype.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := euo.mutation.EQUIPMENTTYPE(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: equipmenttype.FieldEQUIPMENTTYPE,
		})
	}
	if nodes := euo.mutation.RemovedEquipmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipmenttype.EquipmentTable,
			Columns: []string{equipmenttype.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.EquipmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipmenttype.EquipmentTable,
			Columns: []string{equipmenttype.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := euo.mutation.RemovedEquipmentrentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipmenttype.EquipmentrentalTable,
			Columns: []string{equipmenttype.EquipmentrentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipmentrental.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.EquipmentrentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   equipmenttype.EquipmentrentalTable,
			Columns: []string{equipmenttype.EquipmentrentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipmentrental.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	e = &Equipmenttype{config: euo.config}
	_spec.Assign = e.assignValues
	_spec.ScanValues = e.scanValues()
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{equipmenttype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return e, nil
}
