// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/G16/app/ent/bookcourse"
	"github.com/G16/app/ent/equipmentrental"
	"github.com/G16/app/ent/member"
	"github.com/G16/app/ent/payment"
	"github.com/G16/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// MemberUpdate is the builder for updating Member entities.
type MemberUpdate struct {
	config
	hooks      []Hook
	mutation   *MemberMutation
	predicates []predicate.Member
}

// Where adds a new predicate for the builder.
func (mu *MemberUpdate) Where(ps ...predicate.Member) *MemberUpdate {
	mu.predicates = append(mu.predicates, ps...)
	return mu
}

// SetMEMBERID sets the MEMBERID field.
func (mu *MemberUpdate) SetMEMBERID(s string) *MemberUpdate {
	mu.mutation.SetMEMBERID(s)
	return mu
}

// SetNAME sets the NAME field.
func (mu *MemberUpdate) SetNAME(s string) *MemberUpdate {
	mu.mutation.SetNAME(s)
	return mu
}

// AddPaymentIDs adds the payment edge to Payment by ids.
func (mu *MemberUpdate) AddPaymentIDs(ids ...int) *MemberUpdate {
	mu.mutation.AddPaymentIDs(ids...)
	return mu
}

// AddPayment adds the payment edges to Payment.
func (mu *MemberUpdate) AddPayment(p ...*Payment) *MemberUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return mu.AddPaymentIDs(ids...)
}

// AddBookcourseIDs adds the bookcourse edge to Bookcourse by ids.
func (mu *MemberUpdate) AddBookcourseIDs(ids ...int) *MemberUpdate {
	mu.mutation.AddBookcourseIDs(ids...)
	return mu
}

// AddBookcourse adds the bookcourse edges to Bookcourse.
func (mu *MemberUpdate) AddBookcourse(b ...*Bookcourse) *MemberUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return mu.AddBookcourseIDs(ids...)
}

// AddEquipmentrentalIDs adds the equipmentrental edge to Equipmentrental by ids.
func (mu *MemberUpdate) AddEquipmentrentalIDs(ids ...int) *MemberUpdate {
	mu.mutation.AddEquipmentrentalIDs(ids...)
	return mu
}

// AddEquipmentrental adds the equipmentrental edges to Equipmentrental.
func (mu *MemberUpdate) AddEquipmentrental(e ...*Equipmentrental) *MemberUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return mu.AddEquipmentrentalIDs(ids...)
}

// Mutation returns the MemberMutation object of the builder.
func (mu *MemberUpdate) Mutation() *MemberMutation {
	return mu.mutation
}

// RemovePaymentIDs removes the payment edge to Payment by ids.
func (mu *MemberUpdate) RemovePaymentIDs(ids ...int) *MemberUpdate {
	mu.mutation.RemovePaymentIDs(ids...)
	return mu
}

// RemovePayment removes payment edges to Payment.
func (mu *MemberUpdate) RemovePayment(p ...*Payment) *MemberUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return mu.RemovePaymentIDs(ids...)
}

// RemoveBookcourseIDs removes the bookcourse edge to Bookcourse by ids.
func (mu *MemberUpdate) RemoveBookcourseIDs(ids ...int) *MemberUpdate {
	mu.mutation.RemoveBookcourseIDs(ids...)
	return mu
}

// RemoveBookcourse removes bookcourse edges to Bookcourse.
func (mu *MemberUpdate) RemoveBookcourse(b ...*Bookcourse) *MemberUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return mu.RemoveBookcourseIDs(ids...)
}

// RemoveEquipmentrentalIDs removes the equipmentrental edge to Equipmentrental by ids.
func (mu *MemberUpdate) RemoveEquipmentrentalIDs(ids ...int) *MemberUpdate {
	mu.mutation.RemoveEquipmentrentalIDs(ids...)
	return mu
}

// RemoveEquipmentrental removes equipmentrental edges to Equipmentrental.
func (mu *MemberUpdate) RemoveEquipmentrental(e ...*Equipmentrental) *MemberUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return mu.RemoveEquipmentrentalIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (mu *MemberUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := mu.mutation.MEMBERID(); ok {
		if err := member.MEMBERIDValidator(v); err != nil {
			return 0, &ValidationError{Name: "MEMBERID", err: fmt.Errorf("ent: validator failed for field \"MEMBERID\": %w", err)}
		}
	}
	if v, ok := mu.mutation.NAME(); ok {
		if err := member.NAMEValidator(v); err != nil {
			return 0, &ValidationError{Name: "NAME", err: fmt.Errorf("ent: validator failed for field \"NAME\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(mu.hooks) == 0 {
		affected, err = mu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MemberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mu.mutation = mutation
			affected, err = mu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mu.hooks) - 1; i >= 0; i-- {
			mut = mu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MemberUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MemberUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MemberUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MemberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   member.Table,
			Columns: member.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: member.FieldID,
			},
		},
	}
	if ps := mu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.MEMBERID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldMEMBERID,
		})
	}
	if value, ok := mu.mutation.NAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldNAME,
		})
	}
	if nodes := mu.mutation.RemovedPaymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.PaymentTable,
			Columns: []string{member.PaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: payment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.PaymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.PaymentTable,
			Columns: []string{member.PaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: payment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := mu.mutation.RemovedBookcourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.BookcourseTable,
			Columns: []string{member.BookcourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookcourse.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.BookcourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.BookcourseTable,
			Columns: []string{member.BookcourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookcourse.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := mu.mutation.RemovedEquipmentrentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.EquipmentrentalTable,
			Columns: []string{member.EquipmentrentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipmentrental.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.EquipmentrentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.EquipmentrentalTable,
			Columns: []string{member.EquipmentrentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipmentrental.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// MemberUpdateOne is the builder for updating a single Member entity.
type MemberUpdateOne struct {
	config
	hooks    []Hook
	mutation *MemberMutation
}

// SetMEMBERID sets the MEMBERID field.
func (muo *MemberUpdateOne) SetMEMBERID(s string) *MemberUpdateOne {
	muo.mutation.SetMEMBERID(s)
	return muo
}

// SetNAME sets the NAME field.
func (muo *MemberUpdateOne) SetNAME(s string) *MemberUpdateOne {
	muo.mutation.SetNAME(s)
	return muo
}

// AddPaymentIDs adds the payment edge to Payment by ids.
func (muo *MemberUpdateOne) AddPaymentIDs(ids ...int) *MemberUpdateOne {
	muo.mutation.AddPaymentIDs(ids...)
	return muo
}

// AddPayment adds the payment edges to Payment.
func (muo *MemberUpdateOne) AddPayment(p ...*Payment) *MemberUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return muo.AddPaymentIDs(ids...)
}

// AddBookcourseIDs adds the bookcourse edge to Bookcourse by ids.
func (muo *MemberUpdateOne) AddBookcourseIDs(ids ...int) *MemberUpdateOne {
	muo.mutation.AddBookcourseIDs(ids...)
	return muo
}

// AddBookcourse adds the bookcourse edges to Bookcourse.
func (muo *MemberUpdateOne) AddBookcourse(b ...*Bookcourse) *MemberUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return muo.AddBookcourseIDs(ids...)
}

// AddEquipmentrentalIDs adds the equipmentrental edge to Equipmentrental by ids.
func (muo *MemberUpdateOne) AddEquipmentrentalIDs(ids ...int) *MemberUpdateOne {
	muo.mutation.AddEquipmentrentalIDs(ids...)
	return muo
}

// AddEquipmentrental adds the equipmentrental edges to Equipmentrental.
func (muo *MemberUpdateOne) AddEquipmentrental(e ...*Equipmentrental) *MemberUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return muo.AddEquipmentrentalIDs(ids...)
}

// Mutation returns the MemberMutation object of the builder.
func (muo *MemberUpdateOne) Mutation() *MemberMutation {
	return muo.mutation
}

// RemovePaymentIDs removes the payment edge to Payment by ids.
func (muo *MemberUpdateOne) RemovePaymentIDs(ids ...int) *MemberUpdateOne {
	muo.mutation.RemovePaymentIDs(ids...)
	return muo
}

// RemovePayment removes payment edges to Payment.
func (muo *MemberUpdateOne) RemovePayment(p ...*Payment) *MemberUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return muo.RemovePaymentIDs(ids...)
}

// RemoveBookcourseIDs removes the bookcourse edge to Bookcourse by ids.
func (muo *MemberUpdateOne) RemoveBookcourseIDs(ids ...int) *MemberUpdateOne {
	muo.mutation.RemoveBookcourseIDs(ids...)
	return muo
}

// RemoveBookcourse removes bookcourse edges to Bookcourse.
func (muo *MemberUpdateOne) RemoveBookcourse(b ...*Bookcourse) *MemberUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return muo.RemoveBookcourseIDs(ids...)
}

// RemoveEquipmentrentalIDs removes the equipmentrental edge to Equipmentrental by ids.
func (muo *MemberUpdateOne) RemoveEquipmentrentalIDs(ids ...int) *MemberUpdateOne {
	muo.mutation.RemoveEquipmentrentalIDs(ids...)
	return muo
}

// RemoveEquipmentrental removes equipmentrental edges to Equipmentrental.
func (muo *MemberUpdateOne) RemoveEquipmentrental(e ...*Equipmentrental) *MemberUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return muo.RemoveEquipmentrentalIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (muo *MemberUpdateOne) Save(ctx context.Context) (*Member, error) {
	if v, ok := muo.mutation.MEMBERID(); ok {
		if err := member.MEMBERIDValidator(v); err != nil {
			return nil, &ValidationError{Name: "MEMBERID", err: fmt.Errorf("ent: validator failed for field \"MEMBERID\": %w", err)}
		}
	}
	if v, ok := muo.mutation.NAME(); ok {
		if err := member.NAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "NAME", err: fmt.Errorf("ent: validator failed for field \"NAME\": %w", err)}
		}
	}

	var (
		err  error
		node *Member
	)
	if len(muo.hooks) == 0 {
		node, err = muo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MemberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			muo.mutation = mutation
			node, err = muo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(muo.hooks) - 1; i >= 0; i-- {
			mut = muo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, muo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MemberUpdateOne) SaveX(ctx context.Context) *Member {
	m, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return m
}

// Exec executes the query on the entity.
func (muo *MemberUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MemberUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MemberUpdateOne) sqlSave(ctx context.Context) (m *Member, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   member.Table,
			Columns: member.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: member.FieldID,
			},
		},
	}
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Member.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := muo.mutation.MEMBERID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldMEMBERID,
		})
	}
	if value, ok := muo.mutation.NAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: member.FieldNAME,
		})
	}
	if nodes := muo.mutation.RemovedPaymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.PaymentTable,
			Columns: []string{member.PaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: payment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.PaymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.PaymentTable,
			Columns: []string{member.PaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: payment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := muo.mutation.RemovedBookcourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.BookcourseTable,
			Columns: []string{member.BookcourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookcourse.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.BookcourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.BookcourseTable,
			Columns: []string{member.BookcourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bookcourse.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := muo.mutation.RemovedEquipmentrentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.EquipmentrentalTable,
			Columns: []string{member.EquipmentrentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipmentrental.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.EquipmentrentalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.EquipmentrentalTable,
			Columns: []string{member.EquipmentrentalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: equipmentrental.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	m = &Member{config: muo.config}
	_spec.Assign = m.assignValues
	_spec.ScanValues = m.scanValues()
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return m, nil
}
