// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/G16/app/ent/paymenttype"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Paymenttype is the model entity for the Paymenttype schema.
type Paymenttype struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TYPE holds the value of the "TYPE" field.
	TYPE string `json:"TYPE,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymenttypeQuery when eager-loading is set.
	Edges PaymenttypeEdges `json:"edges"`
}

// PaymenttypeEdges holds the relations/edges for other nodes in the graph.
type PaymenttypeEdges struct {
	// Payment holds the value of the payment edge.
	Payment []*Payment
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PaymentOrErr returns the Payment value or an error if the edge
// was not loaded in eager-loading.
func (e PaymenttypeEdges) PaymentOrErr() ([]*Payment, error) {
	if e.loadedTypes[0] {
		return e.Payment, nil
	}
	return nil, &NotLoadedError{edge: "payment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Paymenttype) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // TYPE
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Paymenttype fields.
func (pa *Paymenttype) assignValues(values ...interface{}) error {
	if m, n := len(values), len(paymenttype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	pa.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field TYPE", values[0])
	} else if value.Valid {
		pa.TYPE = value.String
	}
	return nil
}

// QueryPayment queries the payment edge of the Paymenttype.
func (pa *Paymenttype) QueryPayment() *PaymentQuery {
	return (&PaymenttypeClient{config: pa.config}).QueryPayment(pa)
}

// Update returns a builder for updating this Paymenttype.
// Note that, you need to call Paymenttype.Unwrap() before calling this method, if this Paymenttype
// was returned from a transaction, and the transaction was committed or rolled back.
func (pa *Paymenttype) Update() *PaymenttypeUpdateOne {
	return (&PaymenttypeClient{config: pa.config}).UpdateOne(pa)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (pa *Paymenttype) Unwrap() *Paymenttype {
	tx, ok := pa.config.driver.(*txDriver)
	if !ok {
		panic("ent: Paymenttype is not a transactional entity")
	}
	pa.config.driver = tx.drv
	return pa
}

// String implements the fmt.Stringer.
func (pa *Paymenttype) String() string {
	var builder strings.Builder
	builder.WriteString("Paymenttype(")
	builder.WriteString(fmt.Sprintf("id=%v", pa.ID))
	builder.WriteString(", TYPE=")
	builder.WriteString(pa.TYPE)
	builder.WriteByte(')')
	return builder.String()
}

// Paymenttypes is a parsable slice of Paymenttype.
type Paymenttypes []*Paymenttype

func (pa Paymenttypes) config(cfg config) {
	for _i := range pa {
		pa[_i].config = cfg
	}
}
