/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPayment
 */
export interface ControllersPayment {
    /**
     * 
     * @type {number}
     * @memberof ControllersPayment
     */
    employee?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPayment
     */
    member?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersPayment
     */
    paymentamount?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersPayment
     */
    paymentdate?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersPayment
     */
    paymenttype?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPayment
     */
    promotion?: number;
}

export function ControllersPaymentFromJSON(json: any): ControllersPayment {
    return ControllersPaymentFromJSONTyped(json, false);
}

export function ControllersPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPayment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'employee': !exists(json, 'employee') ? undefined : json['employee'],
        'member': !exists(json, 'member') ? undefined : json['member'],
        'paymentamount': !exists(json, 'paymentamount') ? undefined : json['paymentamount'],
        'paymentdate': !exists(json, 'paymentdate') ? undefined : json['paymentdate'],
        'paymenttype': !exists(json, 'paymenttype') ? undefined : json['paymenttype'],
        'promotion': !exists(json, 'promotion') ? undefined : json['promotion'],
    };
}

export function ControllersPaymentToJSON(value?: ControllersPayment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'employee': value.employee,
        'member': value.member,
        'paymentamount': value.paymentamount,
        'paymentdate': value.paymentdate,
        'paymenttype': value.paymenttype,
        'promotion': value.promotion,
    };
}


