/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersBookcourse
 */
export interface ControllersBookcourse {
    /**
     * 
     * @type {number}
     * @memberof ControllersBookcourse
     */
    access?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersBookcourse
     */
    booktime?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersBookcourse
     */
    course?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersBookcourse
     */
    detail?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersBookcourse
     */
    employee?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBookcourse
     */
    member?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersBookcourse
     */
    phone?: string;
}

export function ControllersBookcourseFromJSON(json: any): ControllersBookcourse {
    return ControllersBookcourseFromJSONTyped(json, false);
}

export function ControllersBookcourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersBookcourse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'access': !exists(json, 'access') ? undefined : json['access'],
        'booktime': !exists(json, 'booktime') ? undefined : json['booktime'],
        'course': !exists(json, 'course') ? undefined : json['course'],
        'detail': !exists(json, 'detail') ? undefined : json['detail'],
        'employee': !exists(json, 'employee') ? undefined : json['employee'],
        'member': !exists(json, 'member') ? undefined : json['member'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
    };
}

export function ControllersBookcourseToJSON(value?: ControllersBookcourse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access': value.access,
        'booktime': value.booktime,
        'course': value.course,
        'detail': value.detail,
        'employee': value.employee,
        'member': value.member,
        'phone': value.phone,
    };
}


