/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPromotionamount
 */
export interface ControllersPromotionamount {
    /**
     * 
     * @type {number}
     * @memberof ControllersPromotionamount
     */
    amount?: number;
}

export function ControllersPromotionamountFromJSON(json: any): ControllersPromotionamount {
    return ControllersPromotionamountFromJSONTyped(json, false);
}

export function ControllersPromotionamountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPromotionamount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
    };
}

export function ControllersPromotionamountToJSON(value?: ControllersPromotionamount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
    };
}


