/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEquipment,
    EntEquipmentFromJSON,
    EntEquipmentFromJSONTyped,
    EntEquipmentToJSON,
    EntEquipmentrental,
    EntEquipmentrentalFromJSON,
    EntEquipmentrentalFromJSONTyped,
    EntEquipmentrentalToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntEquipmenttypeEdges
 */
export interface EntEquipmenttypeEdges {
    /**
     * Equipment holds the value of the equipment edge.
     * @type {Array<EntEquipment>}
     * @memberof EntEquipmenttypeEdges
     */
    equipment?: Array<EntEquipment>;
    /**
     * Equipmentrental holds the value of the equipmentrental edge.
     * @type {Array<EntEquipmentrental>}
     * @memberof EntEquipmenttypeEdges
     */
    equipmentrental?: Array<EntEquipmentrental>;
}

export function EntEquipmenttypeEdgesFromJSON(json: any): EntEquipmenttypeEdges {
    return EntEquipmenttypeEdgesFromJSONTyped(json, false);
}

export function EntEquipmenttypeEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntEquipmenttypeEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'equipment': !exists(json, 'equipment') ? undefined : ((json['equipment'] as Array<any>).map(EntEquipmentFromJSON)),
        'equipmentrental': !exists(json, 'equipmentrental') ? undefined : ((json['equipmentrental'] as Array<any>).map(EntEquipmentrentalFromJSON)),
    };
}

export function EntEquipmenttypeEdgesToJSON(value?: EntEquipmenttypeEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'equipment': value.equipment === undefined ? undefined : ((value.equipment as Array<any>).map(EntEquipmentToJSON)),
        'equipmentrental': value.equipmentrental === undefined ? undefined : ((value.equipmentrental as Array<any>).map(EntEquipmentrentalToJSON)),
    };
}


