/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPromotionamountEdges,
    EntPromotionamountEdgesFromJSON,
    EntPromotionamountEdgesFromJSONTyped,
    EntPromotionamountEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPromotionamount
 */
export interface EntPromotionamount {
    /**
     * AMOUNT holds the value of the "AMOUNT" field.
     * @type {number}
     * @memberof EntPromotionamount
     */
    aMOUNT?: number;
    /**
     * 
     * @type {EntPromotionamountEdges}
     * @memberof EntPromotionamount
     */
    edges?: EntPromotionamountEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntPromotionamount
     */
    id?: number;
}

export function EntPromotionamountFromJSON(json: any): EntPromotionamount {
    return EntPromotionamountFromJSONTyped(json, false);
}

export function EntPromotionamountFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPromotionamount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aMOUNT': !exists(json, 'AMOUNT') ? undefined : json['AMOUNT'],
        'edges': !exists(json, 'edges') ? undefined : EntPromotionamountEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntPromotionamountToJSON(value?: EntPromotionamount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AMOUNT': value.aMOUNT,
        'edges': EntPromotionamountEdgesToJSON(value.edges),
        'id': value.id,
    };
}


