/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Patient
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEmployee,
    EntEmployeeFromJSON,
    EntEmployeeFromJSONTyped,
    EntEmployeeToJSON,
    EntMember,
    EntMemberFromJSON,
    EntMemberFromJSONTyped,
    EntMemberToJSON,
    EntPaymenttype,
    EntPaymenttypeFromJSON,
    EntPaymenttypeFromJSONTyped,
    EntPaymenttypeToJSON,
    EntPromotion,
    EntPromotionFromJSON,
    EntPromotionFromJSONTyped,
    EntPromotionToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPaymentEdges
 */
export interface EntPaymentEdges {
    /**
     * 
     * @type {EntEmployee}
     * @memberof EntPaymentEdges
     */
    employee?: EntEmployee;
    /**
     * 
     * @type {EntMember}
     * @memberof EntPaymentEdges
     */
    member?: EntMember;
    /**
     * 
     * @type {EntPaymenttype}
     * @memberof EntPaymentEdges
     */
    paymenttype?: EntPaymenttype;
    /**
     * 
     * @type {EntPromotion}
     * @memberof EntPaymentEdges
     */
    promotion?: EntPromotion;
}

export function EntPaymentEdgesFromJSON(json: any): EntPaymentEdges {
    return EntPaymentEdgesFromJSONTyped(json, false);
}

export function EntPaymentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPaymentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'employee': !exists(json, 'Employee') ? undefined : EntEmployeeFromJSON(json['Employee']),
        'member': !exists(json, 'Member') ? undefined : EntMemberFromJSON(json['Member']),
        'paymenttype': !exists(json, 'Paymenttype') ? undefined : EntPaymenttypeFromJSON(json['Paymenttype']),
        'promotion': !exists(json, 'Promotion') ? undefined : EntPromotionFromJSON(json['Promotion']),
    };
}

export function EntPaymentEdgesToJSON(value?: EntPaymentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'employee': EntEmployeeToJSON(value.employee),
        'member': EntMemberToJSON(value.member),
        'paymenttype': EntPaymenttypeToJSON(value.paymenttype),
        'promotion': EntPromotionToJSON(value.promotion),
    };
}


