// Code generated by entc, DO NOT EDIT.

package salary

import (
	"github.com/G16/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// SALARY applies equality check predicate on the "SALARY" field. It's identical to SALARYEQ.
func SALARY(v int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSALARY), v))
	})
}

// SALARYEQ applies the EQ predicate on the "SALARY" field.
func SALARYEQ(v int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSALARY), v))
	})
}

// SALARYNEQ applies the NEQ predicate on the "SALARY" field.
func SALARYNEQ(v int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSALARY), v))
	})
}

// SALARYIn applies the In predicate on the "SALARY" field.
func SALARYIn(vs ...int) predicate.Salary {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Salary(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSALARY), v...))
	})
}

// SALARYNotIn applies the NotIn predicate on the "SALARY" field.
func SALARYNotIn(vs ...int) predicate.Salary {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Salary(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSALARY), v...))
	})
}

// SALARYGT applies the GT predicate on the "SALARY" field.
func SALARYGT(v int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSALARY), v))
	})
}

// SALARYGTE applies the GTE predicate on the "SALARY" field.
func SALARYGTE(v int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSALARY), v))
	})
}

// SALARYLT applies the LT predicate on the "SALARY" field.
func SALARYLT(v int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSALARY), v))
	})
}

// SALARYLTE applies the LTE predicate on the "SALARY" field.
func SALARYLTE(v int) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSALARY), v))
	})
}

// HasEmployee applies the HasEdge predicate on the "employee" edge.
func HasEmployee() predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EmployeeTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmployeeWith applies the HasEdge predicate on the "employee" edge with a given conditions (other predicates).
func HasEmployeeWith(preds ...predicate.Employee) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EmployeeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Salary) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Salary) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Salary) predicate.Salary {
	return predicate.Salary(func(s *sql.Selector) {
		p(s.Not())
	})
}
