// Code generated by entc, DO NOT EDIT.

package promotion

import (
	"github.com/G16/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// NAME applies equality check predicate on the "NAME" field. It's identical to NAMEEQ.
func NAME(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNAME), v))
	})
}

// DESC applies equality check predicate on the "DESC" field. It's identical to DESCEQ.
func DESC(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDESC), v))
	})
}

// CODE applies equality check predicate on the "CODE" field. It's identical to CODEEQ.
func CODE(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCODE), v))
	})
}

// NAMEEQ applies the EQ predicate on the "NAME" field.
func NAMEEQ(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNAME), v))
	})
}

// NAMENEQ applies the NEQ predicate on the "NAME" field.
func NAMENEQ(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNAME), v))
	})
}

// NAMEIn applies the In predicate on the "NAME" field.
func NAMEIn(vs ...string) predicate.Promotion {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Promotion(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNAME), v...))
	})
}

// NAMENotIn applies the NotIn predicate on the "NAME" field.
func NAMENotIn(vs ...string) predicate.Promotion {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Promotion(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNAME), v...))
	})
}

// NAMEGT applies the GT predicate on the "NAME" field.
func NAMEGT(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNAME), v))
	})
}

// NAMEGTE applies the GTE predicate on the "NAME" field.
func NAMEGTE(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNAME), v))
	})
}

// NAMELT applies the LT predicate on the "NAME" field.
func NAMELT(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNAME), v))
	})
}

// NAMELTE applies the LTE predicate on the "NAME" field.
func NAMELTE(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNAME), v))
	})
}

// NAMEContains applies the Contains predicate on the "NAME" field.
func NAMEContains(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNAME), v))
	})
}

// NAMEHasPrefix applies the HasPrefix predicate on the "NAME" field.
func NAMEHasPrefix(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNAME), v))
	})
}

// NAMEHasSuffix applies the HasSuffix predicate on the "NAME" field.
func NAMEHasSuffix(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNAME), v))
	})
}

// NAMEEqualFold applies the EqualFold predicate on the "NAME" field.
func NAMEEqualFold(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNAME), v))
	})
}

// NAMEContainsFold applies the ContainsFold predicate on the "NAME" field.
func NAMEContainsFold(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNAME), v))
	})
}

// DESCEQ applies the EQ predicate on the "DESC" field.
func DESCEQ(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDESC), v))
	})
}

// DESCNEQ applies the NEQ predicate on the "DESC" field.
func DESCNEQ(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDESC), v))
	})
}

// DESCIn applies the In predicate on the "DESC" field.
func DESCIn(vs ...string) predicate.Promotion {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Promotion(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDESC), v...))
	})
}

// DESCNotIn applies the NotIn predicate on the "DESC" field.
func DESCNotIn(vs ...string) predicate.Promotion {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Promotion(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDESC), v...))
	})
}

// DESCGT applies the GT predicate on the "DESC" field.
func DESCGT(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDESC), v))
	})
}

// DESCGTE applies the GTE predicate on the "DESC" field.
func DESCGTE(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDESC), v))
	})
}

// DESCLT applies the LT predicate on the "DESC" field.
func DESCLT(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDESC), v))
	})
}

// DESCLTE applies the LTE predicate on the "DESC" field.
func DESCLTE(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDESC), v))
	})
}

// DESCContains applies the Contains predicate on the "DESC" field.
func DESCContains(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDESC), v))
	})
}

// DESCHasPrefix applies the HasPrefix predicate on the "DESC" field.
func DESCHasPrefix(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDESC), v))
	})
}

// DESCHasSuffix applies the HasSuffix predicate on the "DESC" field.
func DESCHasSuffix(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDESC), v))
	})
}

// DESCEqualFold applies the EqualFold predicate on the "DESC" field.
func DESCEqualFold(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDESC), v))
	})
}

// DESCContainsFold applies the ContainsFold predicate on the "DESC" field.
func DESCContainsFold(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDESC), v))
	})
}

// CODEEQ applies the EQ predicate on the "CODE" field.
func CODEEQ(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCODE), v))
	})
}

// CODENEQ applies the NEQ predicate on the "CODE" field.
func CODENEQ(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCODE), v))
	})
}

// CODEIn applies the In predicate on the "CODE" field.
func CODEIn(vs ...string) predicate.Promotion {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Promotion(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCODE), v...))
	})
}

// CODENotIn applies the NotIn predicate on the "CODE" field.
func CODENotIn(vs ...string) predicate.Promotion {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Promotion(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCODE), v...))
	})
}

// CODEGT applies the GT predicate on the "CODE" field.
func CODEGT(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCODE), v))
	})
}

// CODEGTE applies the GTE predicate on the "CODE" field.
func CODEGTE(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCODE), v))
	})
}

// CODELT applies the LT predicate on the "CODE" field.
func CODELT(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCODE), v))
	})
}

// CODELTE applies the LTE predicate on the "CODE" field.
func CODELTE(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCODE), v))
	})
}

// CODEContains applies the Contains predicate on the "CODE" field.
func CODEContains(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCODE), v))
	})
}

// CODEHasPrefix applies the HasPrefix predicate on the "CODE" field.
func CODEHasPrefix(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCODE), v))
	})
}

// CODEHasSuffix applies the HasSuffix predicate on the "CODE" field.
func CODEHasSuffix(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCODE), v))
	})
}

// CODEEqualFold applies the EqualFold predicate on the "CODE" field.
func CODEEqualFold(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCODE), v))
	})
}

// CODEContainsFold applies the ContainsFold predicate on the "CODE" field.
func CODEContainsFold(v string) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCODE), v))
	})
}

// HasPromotiontype applies the HasEdge predicate on the "promotiontype" edge.
func HasPromotiontype() predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PromotiontypeTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PromotiontypeTable, PromotiontypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPromotiontypeWith applies the HasEdge predicate on the "promotiontype" edge with a given conditions (other predicates).
func HasPromotiontypeWith(preds ...predicate.Promotiontype) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PromotiontypeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PromotiontypeTable, PromotiontypeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPromotionamount applies the HasEdge predicate on the "promotionamount" edge.
func HasPromotionamount() predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PromotionamountTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PromotionamountTable, PromotionamountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPromotionamountWith applies the HasEdge predicate on the "promotionamount" edge with a given conditions (other predicates).
func HasPromotionamountWith(preds ...predicate.Promotionamount) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PromotionamountInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PromotionamountTable, PromotionamountColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPromotiontime applies the HasEdge predicate on the "promotiontime" edge.
func HasPromotiontime() predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PromotiontimeTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PromotiontimeTable, PromotiontimeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPromotiontimeWith applies the HasEdge predicate on the "promotiontime" edge with a given conditions (other predicates).
func HasPromotiontimeWith(preds ...predicate.Promotiontime) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PromotiontimeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PromotiontimeTable, PromotiontimeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPayment applies the HasEdge predicate on the "payment" edge.
func HasPayment() predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PaymentTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentTable, PaymentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentWith applies the HasEdge predicate on the "payment" edge with a given conditions (other predicates).
func HasPaymentWith(preds ...predicate.Payment) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PaymentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentTable, PaymentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Promotion) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Promotion) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Promotion) predicate.Promotion {
	return predicate.Promotion(func(s *sql.Selector) {
		p(s.Not())
	})
}
