// Code generated by entc, DO NOT EDIT.

package bookcourse

import (
	"time"

	"github.com/G16/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// BOOKTIME applies equality check predicate on the "BOOKTIME" field. It's identical to BOOKTIMEEQ.
func BOOKTIME(v time.Time) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBOOKTIME), v))
	})
}

// BOOKTIMEEQ applies the EQ predicate on the "BOOKTIME" field.
func BOOKTIMEEQ(v time.Time) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBOOKTIME), v))
	})
}

// BOOKTIMENEQ applies the NEQ predicate on the "BOOKTIME" field.
func BOOKTIMENEQ(v time.Time) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldBOOKTIME), v))
	})
}

// BOOKTIMEIn applies the In predicate on the "BOOKTIME" field.
func BOOKTIMEIn(vs ...time.Time) predicate.Bookcourse {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Bookcourse(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldBOOKTIME), v...))
	})
}

// BOOKTIMENotIn applies the NotIn predicate on the "BOOKTIME" field.
func BOOKTIMENotIn(vs ...time.Time) predicate.Bookcourse {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Bookcourse(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldBOOKTIME), v...))
	})
}

// BOOKTIMEGT applies the GT predicate on the "BOOKTIME" field.
func BOOKTIMEGT(v time.Time) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldBOOKTIME), v))
	})
}

// BOOKTIMEGTE applies the GTE predicate on the "BOOKTIME" field.
func BOOKTIMEGTE(v time.Time) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldBOOKTIME), v))
	})
}

// BOOKTIMELT applies the LT predicate on the "BOOKTIME" field.
func BOOKTIMELT(v time.Time) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldBOOKTIME), v))
	})
}

// BOOKTIMELTE applies the LTE predicate on the "BOOKTIME" field.
func BOOKTIMELTE(v time.Time) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldBOOKTIME), v))
	})
}

// HasCourse applies the HasEdge predicate on the "course" edge.
func HasCourse() predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CourseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CourseTable, CourseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCourseWith applies the HasEdge predicate on the "course" edge with a given conditions (other predicates).
func HasCourseWith(preds ...predicate.Course) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CourseInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CourseTable, CourseColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEmployee applies the HasEdge predicate on the "employee" edge.
func HasEmployee() predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EmployeeTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmployeeWith applies the HasEdge predicate on the "employee" edge with a given conditions (other predicates).
func HasEmployeeWith(preds ...predicate.Employee) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EmployeeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMember applies the HasEdge predicate on the "member" edge.
func HasMember() predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MemberTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberWith applies the HasEdge predicate on the "member" edge with a given conditions (other predicates).
func HasMemberWith(preds ...predicate.Member) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MemberInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Bookcourse) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Bookcourse) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bookcourse) predicate.Bookcourse {
	return predicate.Bookcourse(func(s *sql.Selector) {
		p(s.Not())
	})
}
